# Generated by Django 5.2.6 on 2025-11-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='level',
            field=models.CharField(choices=[('degree1', 'degree year 1'), ('degree2', 'degree year 2'), ('degree3', 'degree year 3'), ('degree4', 'degree year 4'), ('diploma1', 'diploma year 1'), ('diploma2', 'diploma year 2')], max_length=100, null=True),
        ),
    ]
