# Generated by Django 5.2.6 on 2025-11-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_resource_semester_faculty_resource_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='univesity',
            new_name='university',
        ),
    ]
