# Generated by Django 5.2.6 on 2025-11-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_rename_univesity_course_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
